version : '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      STAGE: local
      DOMAINS: 'localhost -> http://nodejs:3000'
      # DOMAINS: 'wordpress.example.com -> http://localhost:3000'
      # STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
    links: 
      -  nodejs
    volumes: 
      - ./https-portal-data:/var/lib/https-portal
  db:
    image: mysql:5.7.16
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --port 3333
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3333:3333"
    expose:
      - 3333
    volumes:
      - ./mysql/data:/var/lib/mysql  # mysqlのデータを永続化
      - ./mysql/init:/docker-entrypoint-initdb.d  # コンテナ起動時にSQLを発行
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf  # 設定ファイルをバインド
  nodejs:
    build: app
    # image: node-express-dev:1.0
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    command: node /app/index.js