version : '3'
services:
  db:
    image: mysql:5.7.16
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --port 3333
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3333:3333"
    expose:
      - 3333
    volumes:
      - ./mysql/data:/var/lib/mysql  # mysqlのデータを永続化
      - ./mysql/init:/docker-entrypoint-initdb.d  # コンテナ起動時にSQLを発行
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf  # 設定ファイルをバインド
  nodejs:
    image: node:12
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./app:/var/app
    command: node /var/app/index.js